var SHEET_NAME="Members";var ADMIN_ID="RashtriyaAdmin";var ADMIN_PASSWORD="ChangeMe@12345";
function doGet(e){return response({success:true,message:"RashtriyaSenaa API is working"});}
function doPost(e){try{var d=JSON.parse(e.postData.contents);if(d.action==="adminLogin")return adminLogin(d);if(d.action==="adminList")return adminList(d);if(d.action==="adminAction")return adminAction(d);if(d.action==="register")return register(d);if(d.action==="status")return status(d);if(d.action==="login")return memberLogin(d);return response({success:false,message:"Invalid action"});}catch(x){return response({success:false,message:x.toString()});}}
function getSheet(){var s=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEET_NAME);if(!s){s=SpreadsheetApp.getActiveSpreadsheet().insertSheet(SHEET_NAME);s.appendRow(["Application ID","Member ID","Name","Father Name","Mobile","Email","DOB","Address","District","State","Photo","Status","Applied Date"]);}return s;}
function adminLogin(d){var ok=String(d.adminId)===ADMIN_ID&&String(d.password)===ADMIN_PASSWORD;return response({success:ok,message:ok?"Admin login successful":"Invalid Admin ID or Password"});}
function adminList(d){if(!isAdmin(d))return response({success:false,message:"Unauthorized"});var v=getSheet().getDataRange().getValues(),a=[];for(var i=1;i<v.length;i++)a.push({applicationId:v[i][0],memberId:v[i][1],name:v[i][2],fatherName:v[i][3],mobile:v[i][4],email:v[i][5],dob:v[i][6],address:v[i][7],district:v[i][8],state:v[i][9],photo:v[i][10],status:v[i][11],appliedDate:v[i][12]});return response({success:true,applications:a});}
function adminAction(d){if(!isAdmin(d))return response({success:false,message:"Unauthorized"});var s=getSheet(),v=s.getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][0])===String(d.applicationId)){if(String(d.actionType)==="approve"){var id="RS-M-"+new Date().getTime();s.getRange(i+1,2).setValue(id);s.getRange(i+1,12).setValue("APPROVED");return response({success:true,message:"Application approved",memberId:id});}if(String(d.actionType)==="reject"){s.getRange(i+1,12).setValue("REJECTED");return response({success:true,message:"Application rejected"});}}return response({success:false,message:"Application not found"});}
function register(d){var id="RS-"+new Date().getTime();getSheet().appendRow([id,"",d.name||"",d.fatherName||"",d.mobile||"",d.email||"",d.dob||"",d.address||"",d.district||"",d.state||"",d.photo||"","PENDING",new Date()]);return response({success:true,applicationId:id,status:"PENDING"});}
function status(d){var v=getSheet().getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][0])===String(d.applicationId)&&String(v[i][4])===String(d.mobile))return response({success:true,applicationId:v[i][0],memberId:v[i][1],name:v[i][2],status:v[i][11]});return response({success:false,message:"Application not found"});}
function memberLogin(d){var v=getSheet().getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][1])===String(d.memberId)&&String(v[i][4])===String(d.mobile)){if(String(v[i][11])!=="APPROVED")return response({success:false,message:"Application is not approved yet"});return response({success:true,memberId:v[i][1],name:v[i][2],status:"APPROVED"});}return response({success:false,message:"Invalid Member ID or Mobile Number"});}
function isAdmin(d){return String(d.adminId)===ADMIN_ID&&String(d.password)===ADMIN_PASSWORD;}
function response(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON);}
